---
title: "econ-assignment2"
author: "Jessica Jagdeo"
date: "April 22, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}

library(tidyverse)

gas <- read_csv("Gas_Data.csv")
```

If we’re going to use linear regression, we should have reason to think that a linear relationship exists between variables.

```{r}

gaslow_scatter <- ggplot(gas, aes(x = Q_Low_Gallons_per_Day, y = Price_Dollars)) +
  geom_point()

gaslow_scatter

gashigh_scatter <- ggplot(gas, aes(x = Q_High_Gallons_per_Day, y = Price_Dollars)) +
  geom_point()

gashigh_scatter

#The data display very rough linear relationships

```

```{r}

# The general syntax for linear regression in R is: model_name <- lm(y_variable ~ x_variable, data = df_name)

gaslow_model <- lm(Price_Dollars ~ Q_Low_Gallons_per_Day, data = gas)

gaslow_model

#Low Gas Price = 21.991 - 0.0001355(Q_Low_Gallons_per_Day)

gashigh_model <- lm(Price_Dollars ~ Q_High_Gallons_per_Day, data = gas)

gashigh_model

#High Gas Price = 23.391 - 0.0001297(Q_High_Gallons_per_Day)

# In the context of this model, the slope means that for every gallon of gas, there is a decrease in the willingness to pay.

```

```{r}

par(mfrow = c(2,2))

plot(gaslow_model)

```
```{r}

summary(gaslow_model)

# Coefficient of determination R^2: 0.705. Quantity of gas significantly predicts price, according to this model. 

# 71% of variance in gas prices is explained by the quantity.

```

```{r}

gas_graph <- ggplot(gas, aes(x = Price_Dollars, y = Q_Low_Gallons_per_Day)) +
geom_point() +
geom_smooth(method = lm, se = TRUE, size = 0.5, color = "gray20") +
theme_bw() +
labs(x = "Quantity", y = "Price")

gas_graph

```

```{r}

# To create the supply curve, we must find the equation for the line. We can do so because we know the curve hits the price acis at (0,0) and must intersect aggregate demand at a price of $5.

# Low Gas Price = 21.991 - 0.0001355(Q_Low_Gallons_per_Day)

(5-21.991)/-0.0001355

# Supply curve intersects the low gas demand curve at (5, 125394.8). 

125394.8/5

# Supply curve is Price = 25078.96(Quantity of Gas)


```

```{r}

#defining the aggregate demand curve

aggdemand <- function(x) {
  -0.00006626828808*x + 22.7063092
}

#defining the supply curve

supply <- function(x) {
  0.00001871318504*x 
}

#defining marginal environmental cost

MEC <- function(x) {
  2
}

#defining low income demand

 lowincome <- function(x) {
   -0.0001355*x +21.991
 }
 
 highincome <- function(x) {
   -0.0001297*x + 23.391
 }
 

```


```{r}

#attempting to graph the demand, supply, and MEC curves

gasplot <- ggplot(data.frame(x = c(0,400000)), aes(x = x))+
  stat_function(fun = aggdemand, colour = "red")+
  stat_function(fun = supply, colour = "blue")+
  stat_function(fun = MEC)+
  stat_function(fun = lowincome, colour = "green")+
  stat_function(fun = highincome)+
  theme_classic()+
  ylim(0,30)


gasplot

```


```{r}

#Calculations with the $0.50 tax

#define new supply function with tax added

supply_tax <- function(x) {
  0.00001871318504*x +0.50
}  

```

```{r}
#new graph with new supply curve

gasplot_tax <- ggplot(data.frame(x = c(0,400000)), aes(x = x)) +
  stat_function(fun = aggdemand, colour = "red")+
  stat_function(fun = supply_tax, colour = "blue")+
  stat_function(fun = MEC)+
  stat_function(fun = lowincome, colour = "green")+
  stat_function(fun = highincome, colour = "purple")+
  ylim(0,30)+
  theme_classic()+
  labs(x = "Quantity of Gasoline Consumed (gallons)", y = "Price")
  


gasplot_tax

```

```{r}
# defining new demnd curves with intercepts halfed for #5 

lowincome_half <- function(x) {
   -0.0001355*x + 10.9955
 }

highincome_half <-function(x) {
  -0.0001297*x + 11.6955
}


aggdemand_half <-function(x) {
   -0.00006626828808*x + 11.35410113
}
```


```{r}
#5. New demand curves with electric car alternative

gasplot_EC <- ggplot(data.frame(x = c(0,400000)), aes(x = x)) +
  stat_function(fun = aggdemand_half, colour = "red")+
  stat_function(fun = supply_tax, colour = "blue")+
  stat_function(fun = MEC)+
  stat_function(fun = lowincome_half, colour = "green")+
  stat_function(fun = highincome_half, colour = "purple")+
  ylim(0,20)+
  theme_classic()+
  labs(x = "Quantity of Gasoline Consumed (gallons)", y = "Price")
  


gasplot_EC

```

